//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Be.HexEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentFiles"]));
            }
            set {
                this["RecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int RecentFilesMax {
            get {
                return ((int)(this["RecentFilesMax"]));
            }
            set {
                this["RecentFilesMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseSystemLanguage {
            get {
                return ((bool)(this["UseSystemLanguage"]));
            }
            set {
                this["UseSystemLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedLanguage {
            get {
                return ((string)(this["SelectedLanguage"]));
            }
            set {
                this["SelectedLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string" +
            ">\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10<" +
            "/string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X" +
            " 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <st" +
            "ring>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>" +
            "\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</" +
            "string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X " +
            "8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <str" +
            "ing>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r" +
            "\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</s" +
            "tring>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8" +
            "X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <stri" +
            "ng>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n" +
            "  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</st" +
            "ring>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X" +
            " 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <strin" +
            "g>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n " +
            " <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</str" +
            "ing>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X " +
            "10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string" +
            ">9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n  " +
            "<string>9X 8X 10</string>\r\n  <string>9X 8X 10</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Filters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Filters"]));
            }
            set {
                this["Filters"] = value;
            }
        }
    }
}
